# Generated by Django 5.2 on 2025-05-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rati', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isdelete',
            field=models.BooleanField(default=True),
        ),
    ]
