# Generated by Django 5.2 on 2025-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rati', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='rati.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
