# Generated by Django 5.2 on 2025-05-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rati', '0006_remove_rent_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
